spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: thisprojectisforecommercesapplicationwithprovidingsecurityusingjwt
  expiration: 3600000

server:
  port: 8082